name: CI Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo -H apt-get update -y
          sudo -H apt-get install -y libdbus-1-dev
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: "3.16.x"
      - name: Compile Lib for Ubuntu
        run: |
          mkdir $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j4
          sudo make install
      - name: Compile Examples for Ubuntu with local lib
        run: |
          mkdir $GITHUB_WORKSPACE/build_examples_local
          cd $GITHUB_WORKSPACE/build_examples_local
          cmake -DCMAKE_BUILD_TYPE=Release -DSIMPLEDBUS_LOCAL=ON ../examples
          make -j4
      - name: Compile Examples for Ubuntu with system lib
        run: |
          mkdir $GITHUB_WORKSPACE/build_examples_system
          cd $GITHUB_WORKSPACE/build_examples_system
          cmake -DCMAKE_BUILD_TYPE=Release -DSIMPLEDBUS_LOCAL=OFF ../examples
          make -j4
