name: CI Test

on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  build-linux:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        env:
            DEBIAN_FRONTEND: noninteractive  
        run: |
          sudo -H apt-get update -y
          sudo -H apt-get install -y dbus libdbus-1-dev python3-dev libgtest-dev
          sudo -H pip3 install -r $GITHUB_WORKSPACE/test/requirements.txt
      - name: Start DBus
        run: |
          echo "DBUS_SESSION_BUS_ADDRESS=$(dbus-daemon --config-file=/usr/share/dbus-1/session.conf --print-address --fork | cut -d, -f1)" >> $GITHUB_ENV
      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: "3.16.x"
      - name: Compile tests
        run: |
          mkdir $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          cmake -DCMAKE_BUILD_TYPE=Release ../test
          make -j4
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/build
          ./simpledbus_test
